# Generated by Django 3.0.8 on 2020-07-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('vid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('timeStamps', models.TextField(blank=True, null=True)),
                ('blocked', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SecretLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarker.VideoData', verbose_name='video')),
            ],
        ),
    ]
