# Generated by Django 3.0.8 on 2020-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('vid', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('timeStamps', models.TextField(blank=True, null=True)),
                ('blocked', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
