# Generated by Django 3.0.8 on 2020-07-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
