# Generated by Django 3.0.8 on 2020-07-14 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretlink',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
