# Generated by Django 3.0.8 on 2020-08-20 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_play', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
