# Generated by Django 3.0.8 on 2020-07-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0002_secretlink_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretlink',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='bookmarker.VideoData', verbose_name='video'),
        ),
    ]
