# Generated by Django 3.0.8 on 2020-07-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0003_auto_20200725_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='timestamps',
            field=models.TextField(default=''),
        ),
    ]
