# Generated by Django 3.0.8 on 2020-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0003_auto_20200710_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
