# Generated by Django 3.0.8 on 2020-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0004_videodata_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='vid',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
