# Generated by Django 3.0.8 on 2020-07-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0005_auto_20200711_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='blocked',
            field=models.CharField(default='', max_length=10),
        ),
    ]
