# Generated by Django 3.0.8 on 2020-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarker', '0006_auto_20200711_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='blocked',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
