# Generated by Django 3.0.8 on 2020-08-09 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dur', models.PositiveIntegerField(default=0)),
                ('purpose', models.CharField(choices=[('Token', 'Token'), ('Subscription', 'Subscription')], max_length=20)),
                ('token_amount', models.PositiveIntegerField(default=0)),
                ('subscription_duration', models.PositiveIntegerField(default=0)),
                ('max_use', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='promo_code.PromoCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userpromocode',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='user_promo_codes'),
        ),
    ]
