# Generated by Django 3.0.8 on 2020-07-29 04:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBase',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('user', models.ManyToManyField(related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionCode',
            fields=[
                ('promobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promo_code.PromoBase')),
                ('subscription_duration', models.DurationField(default=datetime.timedelta(days=30))),
            ],
            bases=('promo_code.promobase',),
        ),
        migrations.CreateModel(
            name='TokenCode',
            fields=[
                ('promobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promo_code.PromoBase')),
                ('token_amount', models.PositiveIntegerField(default=0)),
            ],
            bases=('promo_code.promobase',),
        ),
    ]
